# Generated by Django 5.1.6 on 2025-02-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_roomimage_room_type_roomimage_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room_type',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype'),
        ),
    ]
